# Puerto de Render
server.port=${PORT:10000}

# CONEXIÓN DIRECTA A LA BASE DE DATOS
spring.datasource.url=jdbc:postgresql://usuario_crud:CB8KWvWgQBIW1a2JfVYxsx2r0OuHtcm2@dpg-db0s3dk9v7es73cpoq8g-a/crud_db_ahlr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect